spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}
    publisher-confirm-type: correlated
    publisher-returns: true

hl7:
  server:
    port: ${HL7_SERVER_PORT:2575}
  rabbitmq:
    exchange: ${HL7_EXCHANGE:hl7.inbound.exchange}
    queue: ${HL7_QUEUE:hl7.inbound.queue}
    routing-key: ${HL7_ROUTING_KEY:hl7.inbound.raw}